### PR TITLE
SCT-58 Ignore temp narratives in event generator

### PR DESCRIPTION
**Pull request by MrCreosote**
tested manually

@briehl - needs review

### CODE REVIEW

**Comment by MrCreosote** [comment]
Related PRs:
https://github.com/kbase/workspace_deluxe/pull/199
kbaseapps/NarrativeService#43
kbase/narrative#1227

**Comment by MrCreosote** [comment]
Need to handle older temp narratives here

**Comment by MrCreosote** [comment]
@briehl ready for re-review

**Comment by briehl** [comment]
looks fine

**Comment by MrCreosote** [comment]
Ok, there's been plenty of time for ppl to review this, and the other 3 related PRs are merged, so merging.

**Pull request merged**
